# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'mytest']

# Cell
def say_hello(to):
    "Say hello to somebody..."
    return f'Hello {to}!'

# Cell
def mytest():
    print("Just something different in the notebook to trigger a rebuild")